name: Roel Christian Yambao
title: Roel Christian Yambao
description: "Roel Christian's personal website."
url: "https://roelchristian.com"
author: Roel Christian Yambao
markdown: kramdown
permalink: /blog/:year/:title

