[[redirects]]
  from = "/assets/pub_cv.pdf"
  to = "/me/cv/cv_en.pdf"
  status = 301
  force = true
  
[[redirects]]
  from = "/cv"
  to = "/me/cv/cv_en.pdf"
  status = 301
  force = true

[[redirects]]
  from = "/connect"
  to = "/contact"
  status = 301
  force = true

[build]
command = "bundle exec jekyll build"
publish = "_site"

[build.environment]
RUBY_VERSION = "3.3.10"
JEKYLL_ENV = "production"

